apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress.name" . }}-mysql
  labels:
    {{- include "wordpress.mysql.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.mysql.pvc.storageClassName }}
  accessModes:
    {{- toYaml .Values.mysql.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.mysql.pvc.size }}

# Made with Bob
