apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.name" . }}-mysql
  labels:
    {{- include "wordpress.mysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: 3306
  selector:
    {{- include "wordpress.mysql.selectorLabels" . | nindent 4 }}

# Made with Bob
