apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.name" . }}-mysql-pass
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.mysql.password | b64enc | quote }}

# Made with Bob
