apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.name" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wordpress.selectorLabels" . | nindent 6 }}
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "wordpress.selectorLabels" . | nindent 8 }}
        tier: frontend
    spec:
      containers:
      - name: wordpress
        image: "{{ .Values.wordpress.image.repository }}:{{ .Values.wordpress.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.wordpress.image.pullPolicy }}
        env:
        - name: WORDPRESS_DB_HOST
          value: {{ include "wordpress.name" . }}-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "wordpress.name" . }}-mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: {{ include "wordpress.name" . }}

# Made with Bob
