apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.name" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  type: {{ .Values.wordpress.service.type }}
  ports:
    - port: {{ .Values.wordpress.service.port }}
      targetPort: 80
  selector:
    {{- include "wordpress.selectorLabels" . | nindent 4 }}
    tier: frontend

# Made with Bob
