kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "filebrowser.name" . }}
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
# Using configMap subPath to mount a file in a pod.
# Resource: https://dev.to/joshduffney/kubernetes-using-configmap-subpaths-to-mount-files-3a1i
data:
  .filebrowser.json: |
    {{- .Values.config | toPrettyJson | nindent 4 }}
