kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "filebrowser.name" . }}
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
spec:
  host: ''
  to:
    kind: Service
    name: {{ include "filebrowser.name" . }}
    weight: 100
  port:
    targetPort: {{ .Values.config.port }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
