apiVersion: v1
kind: Service
metadata:
  name: {{ include "filebrowser.name" . }}
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.config.port }}
  selector:
    {{- include "filebrowser.selectorLabels" . | nindent 4 }}
